---
- hosts: 54.246.59.131
  become: True
  tasks:
    - name: Install Apahe Server
      yum:
        name: httpd
        state: present
    - name: Enable Apache Server
      service:
       name: httpd
       enabled: True
    - name: Install git
      yum:
        name: git
        state: present
...
